# Form implementation generated from reading ui file 'ventana1.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModifyWindow(object):
    def cerrarVentana(self, main_w, modify_w):
        main_w.show()
        modify_w.close()

    def setupUi(self, ModifyWindow, MainWindow):
        ModifyWindow.setObjectName("ModifyWindow")
        ModifyWindow.resize(1261, 552)
        ModifyWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n" "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=ModifyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(parent=self.centralwidget)
        self.background.setGeometry(QtCore.QRect(10, 0, 1241, 511))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("images/Add_products_screen.jpg"))
        self.background.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.background.setObjectName("background")

        # Etiquetas
        self.userLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.userLabel.setGeometry(QtCore.QRect(130, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userLabel.setFont(font)
        self.userLabel.setText("profe")
        self.userLabel.setObjectName("userLabel")

        # Interfaz botones con operaciones lambda
        self.btnVolver = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.cerrarVentana(MainWindow, ModifyWindow))    #lambda
        self.btnVolver.setGeometry(QtCore.QRect(248, 80, 81, 41))
        self.btnVolver.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btnVolver.setObjectName("btnVolver")
        self.btnAgregar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(462, 452, 75, 41))
        self.btnAgregar.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btnAgregar.setObjectName("btnAgregar")
        self.btnQuitar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnQuitar.setGeometry(QtCore.QRect(1116, 452, 75, 41))
        self.btnQuitar.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.btnQuitar.setObjectName("btnQuitar")

        ModifyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ModifyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1261, 21))
        self.menubar.setObjectName("menubar")
        ModifyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ModifyWindow)
        self.statusbar.setObjectName("statusbar")
        ModifyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ModifyWindow)
        QtCore.QMetaObject.connectSlotsByName(ModifyWindow)

    def retranslateUi(self, ModifyWindow):
        _translate = QtCore.QCoreApplication.translate
        ModifyWindow.setWindowTitle(_translate("ModifyWindow", "MainWindow"))
        self.btnVolver.setText(_translate("ModifyWindow", "Volver"))
        self.btnAgregar.setText(_translate("ModifyWindow", "Agregar"))
        self.btnQuitar.setText(_translate("ModifyWindow", "Quitar"))
